/*
 * This source file was generated by the Gradle 'init' task
 */
package user_steam;

import user_steam.SteamProfileService;
import java.util.Scanner;

public class App {

    


    public static void main(String[] args) {

        SteamProfileService steamProfileService = new SteamProfileService();
        
        steamProfileService.setId("76561197960435530"); // Id do usuário que queremos vizualizar

        System.out.println("TESTE -> nome: " + steamProfileService.getRealName());
        System.out.println("TESTE -> URL do perfil: " + steamProfileService.getProfileURL());
        System.out.println("TESTE -> avatar: " + steamProfileService.getAvatar());
        System.out.println("TESTE -> estado: " + steamProfileService.getState());
        /*
        // 1. Configure sua chave API (obtenha em: https://steamcommunity.com/dev)
        String apiKey = "64CF62356550A8ED4570487F17804A85";
        List<String> steamIds = Collections.singletonList("76561197960435530");

        // 2. Crie o cliente da API
        SteamWebApiClient client = new SteamWebApiClient.SteamWebApiClientBuilder(apiKey).build();

        GetPlayerSummariesRequest request = SteamWebApiRequestFactory.createGetPlayerSummariesRequest(steamIds);
        
        try {
            GetPlayerSummaries response = client.<GetPlayerSummaries> processRequest(request);

            if (!response.getResponse().getPlayers().isEmpty()) {
                Player player = response.getResponse().getPlayers().get(0);
                System.out.println("Nome do usuario: " + player.getPersonaname());
                System.out.println("URL do perfil: " + player.getProfileurl());
                System.out.println("Status: " + 
                    (player.getPersonastate() == 1 ? "Online" : "Offline"));
            } else {
                System.out.println("Nenhum jogador encontrado com esse ID.");
            }
        } catch (SteamApiException e) {
            e.printStackTrace();
        }
        */
    }
}



